version: "2.1"
services:
  spring-boot-jwt-auth:
    build: .
    image: spring-boot-jwt-auth-img
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testdb?useSSL=false
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure

  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "testdb"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql

volumes:
  db: